Fix subproject build
Use add_project_arguments instead of add_global_arguments

Fixes:
ERROR: Function 'add_global_arguments' cannot be used in subprojects because there is no way to make that reliable.